name: Alge
author: vapez
version: 3.2
api-version: 1.14
main: de.vapez2k.plugin.main.Main


commands:
   scare:
      description: Scares other players to death.
   gm:
      description: A faster way of switching beetween different Gamemodes.
   h:
      description: A faster method to heal you or other players.
   f:
      description: A faster method to enable flying for you or other players.
   rename:
      description: Rename yourself to whatever you want.
   setwarp:
      description: Sets a warp-point which you can teleport to.
   warp:
      description: Teleport to selected warp.
   setspawn:
      description: Sets the world spawn of the current world.
   spawn:
      description: Teleport to spawn.
   dia: 
      description: Don't know what that does.
   home:
      description: Teleport to one of your private warps.
   sethome:
      description: Set a private warp for you to use.
   delhome:
      description: Delete one of your homes.
   delwarp:
      description: Delete one of the warps you have set.
   rehome:
      description: Rename one of your homes.
   rewarp:
      description: Rename one of the warps you have set.
   listhomes:
      description: List all of your homes.
   listwarps:
      description: List all warps.
   rank:
      description: Create, delete, set and remove ranks from players.
   showinv:
      description: Shows the Inventory of the targeted player.